import { Alert, Avatar, Button, Dropdown, Label, Navbar, TextInput } from 'flowbite-react';
import Head from 'next/head';
import Image from 'next/image';
import { RiFileHistoryFill, RiRefundFill, RiSecurePaymentFill } from 'react-icons/ri';
import { MdOutlineQrCodeScanner } from 'react-icons/md';
import { GiBookPile, GiWallet } from 'react-icons/gi';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import SingleTransactionList from '../components/SingleTransactionList';

export default function Home() {


    const router = useRouter();

    const [transactions, setTransactions] = useState([]);


    useEffect(() => {

        let info = JSON.parse(localStorage.getItem('transactions'))?.reverse() || [];
        setTransactions(info);
        
    }, []);


  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-screen max-w-sm mx-auto">

        <div className='flex items-center py-4'>
            <div className='flex items-center space-x-3'>
                <div className='w-8 h-8 bg-black rounded-full'></div>
                <p className='text-xs font-bold'>Hello, Student</p>
            </div>

            <MdOutlineQrCodeScanner className="text-xl text-black ml-auto" />
        </div>

        <div className='flex items-center px-8 py-12 bg-black text-white rounded-2xl'>
            <div className='space-y-2'>
                <p className='text-xs'>Total Payments</p>
                <p className='text-4xl font-bold'>{(transactions.length).toLocaleString()}</p>
            </div>
        </div>

        <div className='grid grid-cols-2 gap-4 py-4'>
            <Link href="/pay-fees" className='p-4 bg-[#18A47E] text-xs text-center text-white rounded-xl'>Pay</Link>
            <Link href="/history" className='p-4 bg-black text-xs text-center text-white rounded-xl'>History</Link>
        </div>

        <div className='py-4'>
            <p className='text-xs font-bold pb-3'>Transactions</p>
            <div className='space-y-3'>
                
                {transactions?.slice(0,5).map(({paymentFor, university:{name}, data: {reference}}) => (
                    <SingleTransactionList 
                        key={reference}
                        name={name}
                        paymentFor={paymentFor}
                        reference={reference}
                    />
                ))}
                
                <div className='flex justify-center'>
                    <Link href="/history" className='inline-block mx-auto rounded-md text-white bg-black py-2 px-4 text-xs font-bold'>More Transactions</Link>
                </div>
            </div>
        </div>

      </main>



    </div>
  )
}
