import Head from 'next/head';
import { useEffect, useState } from 'react';
import SingleTransactionList from '../components/SingleTransactionList';

export default function Home() {

    const [transactions, setTransactions] = useState([]);

    useEffect(() => {

        let info = JSON.parse(localStorage.getItem('transactions'))?.reverse() || [];
        setTransactions(info);
        
      }, []);

  return (
    <div>
      <Head>
        <title>History</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="w-full h-screen max-w-md p-5 mx-auto p-5">

        <p className='text-center font-bold py-4'>History</p>

        <div className='py-4 space-y-4'>

          {transactions.map(({paymentFor, university:{name}, data: {reference}}) => (
              <SingleTransactionList 
                  key={reference}
                  name={name}
                  paymentFor={paymentFor}
                  reference={reference}
              />
          ))}


        </div>

      </main>

    </div>
  )
}
