import { Alert, Button, Label, TextInput } from 'flowbite-react';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { GiGraduateCap } from 'react-icons/gi';

import { HiInformationCircle } from 'react-icons/hi'

export default function Home() {

  const router = useRouter();
  const [form, setForm] = useState({ });
  const [error, setError] = useState(null);

  const handleSubmit = (e) => {
    e.preventDefault();
    if(form.email === "student@unipay.com"){
      if(form.password === "1234"){
        return router.push('/dashboard');
      }
      
      return setError('Password Incorrect');
    }

    return setError('Email Incorrect');
  }

  useEffect(() => {
    setTimeout(() => setError(''),3000);
  }, [error]);

  return (
    <div>
      <Head>
        <title>Unipay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="w-full h-screen max-w-md mx-auto flex flex-col justify-center items-center">

        {/* <div className='space-y-3'>
          <div className=''>
            <input className='px-2 py-1 h-10 min-w-2/3 outline-none rounded-sm' type="text" name='username' />
          </div>

          <div className=''>
            <input className='px-2 py-1 h-10 min-w-2/3 outline-none rounded-sm' type="password" name="password" />
          </div>

          <div className=''>
            <input className='bg-app-primary w-full uppercase fon-bold text-sm px-2 py-1 h-10 min-w-2/3 outline-none rounded-sm' type="submit" name="password" value="submit" />
          </div>
        </div> */}

        {error && 
          <div className='p-4 w-full'>
            <Alert
              color="failure"
              icon={HiInformationCircle}
              className="block w-full"
            >
              <span>
                <span className="font-medium">
                  Error alert!
                </span>
                &nbsp;{error}
              </span>
            </Alert>
          </div>
        }

        <GiGraduateCap className="text-3xl"/>
        <div className='font-extrabold text-3xl text-center mb-5'>unipay</div>

        <form className="flex flex-col gap-4 p-4 w-full max-w-sm" onSubmit={handleSubmit}>
          <div>
            <TextInput
              id="email1"
              type="email"
              placeholder="name@company.com"
              required={true}
              addon="📧"
              onChange={(e) => setForm({...form, email: e.target.value})}
              value={form.email}
              />
          </div>
          <div>
            <TextInput
              id="password1"
              type="password"
              placeholder="password"
              required={true}
              addon="🔑"
              onChange={(e) => setForm({...form, password: e.target.value})}
              value={form.password}
            />
          </div>
          {/* <div className='w-3/4 mx-auto'> */}
            <Button className='w-full' onClick={handleSubmit} type="submit">
              Submit
            </Button>
          {/* </div> */}
        </form>

      </main>

    </div>
  )
}
