import Head from 'next/head';

import { RiFileHistoryFill } from 'react-icons/ri';
import Script from 'next/script';
import { useRouter } from 'next/router';
import Link from 'next/link';


export default function Home() {

  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="w-full h-screen max-w-md mx-auto">


        <div className='p-4 py-20 space-y-4'>

            <Script strategy="afterInteractive" src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></Script>
            <lottie-player src="https://assets9.lottiefiles.com/packages/lf20_pqnfmone.json"  background="transparent"  speed="1"  style={{ width: '150px', height: '150px', margin: 'auto' }} loop autoplay></lottie-player>
        <p className='text-center font-bold py-4'>Transaction Success</p>

            <Link href={`/transaction?reference=${router.query.reference}`} className='flex justify-center'>
                <p className='inline-flex items-center justify-center gap-2 p-3 bg-sky-600 rounded-md bg-transparent text-center text-sm font-bold'>
                    <RiFileHistoryFill className='text-white' />
                    View Transaction
                </p>
            </Link>

        </div>

      </main>

    </div>
  )
}
