import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';

import QRCode from "react-qr-code";

import { BsArrowRight, BsPrinterFill } from 'react-icons/bs';
import { useRouter } from 'next/router';

import spliter from '../hooks/spliter';


// Response
// {
//   message : "Success"
//   redirecturl : "http://localhost:8080/verify?trxref=1669316941348&reference=1669316941348"
//   reference : "1669316941348"
//   response : "Approved"
//   status : "success"
//   trans : "2310511113"
//   trxref : "1669316941348"
// }




export default function Home() {

  const router = useRouter();
  const {reference} = router.query;

  const [transaction, setTransaction] = useState({});

  
  useEffect(() => {

    let info = JSON.parse(localStorage.getItem('transactions')).find(t => t.data.reference === reference);
    setTransaction(info);
    
  }, [reference]);

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="w-full h-screen max-w-md mx-auto">

        <p className='text-center font-bold py-4'>Receipt</p>

        <div className='p-4 space-y-4'>

            <div className='flex justify-between items-center gap-4'>
              <div className='space-y-4'>
                <div className='flex justify-between items-center gap-4'>
                  <div className='relative w-10 h-10 mx-auto'>
                      <Image src={`/img/${transaction?.university?.logo}`} layout="fill" objectFit="cover" />
                  </div>

                  <p className='font-bold '>{transaction?.university?.name}</p>
                </div>

                <p className='text-3xl'>{spliter(reference)}</p>
              </div>

              <div className=''>
                <QRCode 
                  bgColor='#000'
                  fgColor='#fff'
                  size={120}
                  value={reference || "0000000000000"}
                />
              </div>
            </div>

            <div className='bg-[#0c0c0c] divide-y divide-zinc-800 p-4 rounded-lg'>
                <div className='py-2'>
                    <p className='text-xs text-zinc-700'>Type</p>
                    <p className='font-bold'>{transaction?.paymentFor}</p>
                </div>
                <div className='py-2'>
                    <p className='text-xs text-zinc-700'>Fullname</p>
                    <p className='font-bold'>{transaction?.fullname}</p>
                </div>
                <div className='py-2'>
                    <p className='text-xs text-zinc-700'>Email</p>
                    <p className='font-bold'>{transaction?.email}</p>
                </div>
                <div className='py-2'>
                    <p className='text-xs text-zinc-700'>Phone</p>
                    <p className='font-bold'>{transaction?.phone}</p>
                </div>
            </div>

            <p className='font-bold text-4xl text-center'>&#8358;{Number(transaction?.amount).toLocaleString()}</p>

            <div className=''>
                <p onClick={() => window.print()} className='flex items-center justify-center gap-2 p-3 bg-sky-600 rounded-md bg-transparent w-full text-center text-sm font-bold'>
                    Print
                    <BsPrinterFill className='text-white' />
                </p>
            </div>

        </div>

      </main>

    </div>
  )
}
